# Generated by Django 5.1.2 on 2025-12-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de la imagen del destino', max_length=300, null=True),
        ),
    ]
